# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dog Walking - Boarding - Pet Services - Edinburgh | Edinburgh.dog
email: walking@edinburgh.dog
description: Edinburgh Dog Walking and Pet Services is a local family business providing care to your dogs and other pets.
keywords: Edinburgh, Dog, Walking, Pet, Pet Services, Dog Walking, Dog Boarding, Daycare, Day Care, Dog Daycare
#baseurl: "" # the subpath of your site, e.g. /blog

url: "https://edinburgh.dog" # the base hostname & protocol for your site
assets_dir: assets
banner: /assets/banner_large.png
favicon_dir: /assests/favicon
timezone: GMT

# social
telephone_number: 07490644931
twitter_username: EdDogWalking
email: Walking@Edinburgh.Dog
instagram: Edinburgh.Dog
facebook: Edinburgh.Dog
github_username:  keir-rex

source:      .
include: [_pages]
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts

# Build settings
markdown: kramdown
theme: minima

gems:
- jekyll-gallery-generator
- jekyll-feed

sass:
  style: compressed

exclude:
  - "vendor"
  - "bower_components"
  - "bower.json"
  - "Gruntfile.coffee"
  - "node_modules"
  - "Gemfile*"
  - "package.json"
  - "README.md"
  - "Rakefile"
